package com.springcloud.payment_service.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PaymentResultEvent {
    // Event id generated by Payment Service for PaymentCompleted events
    private String eventId;
    private Long bookingId;
    private String paymentStatus;
    private String bookingStatus;
}
